- name: Deploy Hiddify-Manager
  hosts: all 
  become: true
  environment:
    TERM: xterm

  tasks:
    - name: Check if Hiddify is installed
      stat:
        path: /opt/hiddify-manager/current.json
      register: is_installed

    - name: Download Hiddify install script
      get_url:
        url: https://raw.githubusercontent.com/hiddify/Hiddify-Manager/main/common/download.sh
        dest: /tmp/hiddify.sh
        mode: '0775'
      when: not is_installed.stat.exists

    - name: Install Hiddify in non-GUI mode
      shell: |
        export TERM=xterm
        VER=release /tmp/hiddify.sh --no-gui < /dev/null
      when: not is_installed.stat.exists
      ignore_errors: yes

    - name: Get Hiddify status
      shell: |
        . /opt/hiddify-manager/common/utils.sh
        check_hiddify_panel
        jq -r '.panel_links[]' /opt/hiddify-manager/current.json
        echo "Hiddify is installed"
      args:
        chdir: /opt/hiddify-manager
        executable: /bin/bash
      register: hiddify

    - name: Print Hiddify status output
      debug:
        var: hiddify.stdout_lines
